### PR TITLE
Upon adding a new acceptor/connector update the port number to unique

### LINKED ISSUE #204: Upon adding a second acceptor the second acceptor should have a different port number
When the user adds a second acceptor, the two acceptors have the same port number which fails validation.
To fix: adding a nth acceptor should mean that the port of the acceptor should be 5555+n instead of a static 5555.

Add also validation on the ports fields to ensure uniqueness.
Check that this doesn't collide with connectors as well.

### PR DESCRIPTION
**Pull request by Msarawan**
When user adds a new acceptor or connector updated port number to unique instead of a static 5555.
and also added unit tests to verify the logic.

fixes #204

### CODE REVIEW

File: src/shared-components/FormView/BrokerProperties/ConfigurationPage/AcceptorsConfigPage/AcceptorConfigSection/AcceptorConfigPage/AcceptorConfigPage.tsx [hunk 1]
```diff
@@ -176,6 +178,10 @@ export const AcceptorConfigPage: FC<AcceptorProps> = ({
   ];
 
   const { t } = useTranslation();
+  useEffect(() => {
+    setPort(initialPort);
+  }, [initialPort]);
+
```
Comment (lavocatt) [inline src/shared-components/FormView/BrokerProperties/ConfigurationPage/AcceptorsConfigPage/AcceptorConfigSection/AcceptorConfigPage/AcceptorConfigPage.tsx:184]: Please don't use `useEffect` for this, refer to https://react.dev/learn/you-might-not-need-an-effect for more details about why this isn't a good pattern.

File: src/reducers/7.12/reducer.ts [hunk 2]
```diff
@@ -1698,23 +1710,63 @@ export const getConnector = (cr: BrokerCR, name: string) => {
...
+      if (connector.port) {
+        usedPorts.push(connector.port);
+      }
+    });
+    const newPort = generatePortNumber(usedPorts);
+    //console.log(`Generated new port for connector ${configName}: ${newPort}`);
+    return newPort;
   }
+
+  //console.log(`default port 5555 for configName: ${configName}`);
```
Comment (lavocatt) [inline src/reducers/7.12/reducer.ts:1769]: There should not be commented code lines in a PR. Can you clean them all please?

File: src/reducers/7.12/reducer.ts [hunk 3]
```diff
@@ -1698,23 +1710,63 @@ export const getConnector = (cr: BrokerCR, name: string) => {
...
+    const connectors = getAllConnectors(brokerModel);
+    const usedPorts: number[] = [];
+    connectors.forEach((connector) => {
+      if (connector.port) {
+        usedPorts.push(connector.port);
+      }
+    });
+    const newPort = generatePortNumber(usedPorts);
+    //console.log(`Generated new port for connector ${configName}: ${newPort}`);
+    return newPort;
```
Comment (lavocatt) [inline src/reducers/7.12/reducer.ts:1766]: The function `getConfigPort` is a getter function, it's purpose it to give an easy access to some data we care about. It should not be used to generate a port number.

Can you explain me what was your plan for this section of the code? So that we can find a better way to integrate it.

File: src/reducers/7.12/reducer.ts [hunk 4]
```diff
@@ -298,10 +298,18 @@ interface DeletePEMGenerationForAcceptorAction
...
+    port: number;
+  };
 }
 
 interface AddConnectorAction extends ArtemisReducerActionBase {
   operation: ArtemisReducerOperations.addConnector;
+  payload: {
+    name: string;
+    port: number;
+  };
```
Comment (lavocatt) [inline src/reducers/7.12/reducer.ts:312]: By asking the calling code to provide the `name` and `port` to the Add connector action, we're externalizing the logic of producing a unique port number to the UI code. That's making us diverging from the primary goal of the reducer: centralizing the update logic.

What we want to have instead is a addConnector function able to search for a free port.

File: src/reducers/7.12/reducer.ts [hunk 5]
```diff
@@ -1698,23 +1710,63 @@ export const getConnector = (cr: BrokerCR, name: string) => {
...
+};
+
+export const generatePortNumber = (usedPorts: number[]): number => {
+  let port = 5555;
+  while (usedPorts.includes(port)) {
+    port += 1;
+    //console.log('increament port', port);
+  }
+  return port;
+};
```
Comment (lavocatt) [inline src/reducers/7.12/reducer.ts:1724]: There's no need to work with a secondary list of `usedPorts` we can work in place instead. To get a new free port:
Find the biggest port number in all the acceptors, connectors and the console. Then just add +1 to it.

File: src/reducers/7.12/reducer.ts [hunk 6]
```diff
@@ -298,10 +298,18 @@ interface DeletePEMGenerationForAcceptorAction
 
 interface AddAcceptorAction extends ArtemisReducerActionBase {
   operation: ArtemisReducerOperations.addAcceptor;
+  payload: {
+    name: string;
+    port: number;
+  };
```
Comment (lavocatt) [inline src/reducers/7.12/reducer.ts:304]: same comment as for connectors.

File: src/shared-components/FormView/BrokerProperties/ConfigurationPage/AcceptorsConfigPage/AcceptorsConfigPage.tsx [hunk 7]
```diff
@@ -33,13 +34,25 @@ export const AcceptorsConfigPage: FC<AcceptorsConfigProps> = ({ brokerId }) => {
...
     }
     if (configType === ConfigType.connectors) {
+      const newPort = getConfigPort(
+        cr,
+        configType,
+        `connector-${configs.length}`,
+      );
       dispatch({
         operation: ArtemisReducerOperations.addConnector,
+        payload: { name: `connector-${configs.length}`, port: newPort },
```
Comment (lavocatt) [inline src/shared-components/FormView/BrokerProperties/ConfigurationPage/AcceptorsConfigPage/AcceptorsConfigPage.tsx:55]: See, we already can see some logic externalized from the reducer to the frontend code. A hint for you: the correct solution should imply 0 changes to the UI side of the code.

**Review by lavocatt — CHANGES_REQUESTED** [review]
You've made a good first attempt at solving the issue. But this is a hard one. It involves advanced concepts about where the logic should leave and where it shouldn't. I'm expecting that we will have many back and forth on this one, but don't get discouraged, you'll succeed, no doubt.

What to keep in mind when you're working a second iteration of your contribution:

- The reducer owns the logic
- The UI  components are dispatching events, they can't compute what is the free port
- Getters are purely a way to get to existing data, they can't generate some on the fly.
- Only a solution where the UI components are left untouched will be considered valid.

Have a read on react documentation about reducers, and try out the tutorials they provide, it's good learning: https://react.dev/learn/extracting-state-logic-into-a-reducer

**Review by lavocatt — COMMENTED** [review]
That's a very good improvement. Now the two things left to do are:

* improve the algorithm for generating a unique port number
* add tests to make sure this algorithm does what it says it's doing

**Review by lavocatt — COMMENTED** [review]
That's a very good algorithm you've wrote.

Can you add a test that mixes acceptors and connectors please?

like it would add an acceptor, then a connector, then set the port for the first acceptor and then add another connector. With checking the expected value for every acceptors and connectors.

That would complement well the new tests you've already added.

**Review by lavocatt — APPROVED** [review]
This is perfect! Very good job.

**Comment by Msarawan** [comment]
> This is perfect! Very good job.

Thank you...

**Comment by gaohoward** [comment]
@Msarawan @lavocatt Sorry a bit late but just want to add a little note here:
The port value is not necessarily unique between acceptors and connectors. For example when an acceptor port is 5555, the connector's port can also be 5555 too.

**Comment by lavocatt** [comment]
@gaohoward can you create an issue with this please? So we can fix it in a followup PR? thanks

**Comment by Msarawan** [comment]
> @Msarawan @lavocatt Sorry a bit late but just want to add a little note here: The port value is not necessarily unique between acceptors and connectors. For example when an acceptor port is 5555, the connector's port can also be 5555 too.

ohh okay, will fix this with new PR. thanks!!

**Comment by gaohoward** [comment]
> The port value is not necessarily unique between acceptors and connectors. For example when an acceptor port is 5555, the connector's port can also be 5555 too.

will do.
